source 'http://rubygems.org'
gem 'rails', '3.0.3'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'acts-as-taggable-on', '~>2.1.0'
gem 'mysql'
gem 'will_paginate'
gem 'devise'
gem 'nifty-generators'
gem 'omniauth','0.1.6'
gem "mocha", :group => :test
gem 'exception_notification'
gem 'mongrel', '1.2.0.pre2'
gem 'rubyzip'
gem 'dropbox-sdk'
gem 'rack', '1.2.5'